include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_final_fields
    - avoid_unnecessary_containers
    - prefer_single_quotes
    - always_declare_return_types
    - annotate_overrides
    - avoid_classes_with_only_static_members
    - avoid_empty_else
    - avoid_redundant_argument_values
    - avoid_setters_without_getters
    - camel_case_types
    - constant_identifier_names
    - prefer_typing_uninitialized_variables
    - unnecessary_null_checks
    - use_function_type_syntax_for_parameters

analyzer:
  exclude:
    - build/**
    - test/**.g.dart
    - lib/generated/**

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

flutter:
  uses-material-design: true
